apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello-cronjob
  namespace: kube-system
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: shudipta/hello:test
            ports:
            - containerPort: 80
          restartPolicy: OnFailure