apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hello-replicaset
  namespace: kube-system
  labels:
    app: scanner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scanner
  template:
    metadata:
      labels:
        app: scanner
    spec:
      containers:
      - name: hello
        image: shudipta/hello:test
        ports:
        - containerPort: 80