apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-replicationcontroller
  namespace: kube-system
  labels:
    app: scanner
spec:
  replicas: 1
  selector:
    app: scanner
  template:
    metadata:
      labels:
        app: scanner
    spec:
      containers:
      - name: hello
        image: shudipta/hello:test
        ports:
        - containerPort: 80