apiVersion: v1
kind: Service
metadata:
  name: hello-service
  namespace: kube-system
  labels:
    app: scanner
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: scanner
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: labels-statefulset
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: scanner
  serviceName: "labels-service"
  replicas: 1
  template:
    metadata:
      labels:
        app: scanner
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: labels
        image: shudipta/labels-vuln
        ports:
        - containerPort: 80
          name: web